### PR TITLE
Add support for wasm32-unknown-unknown

### PR DESCRIPTION
**Pull request by germania**
Hey,

This PR adds support for a new option in webpack config, `rustTarget: 'wasm32-unknown-unknown'`.  It defaults to `'wasm32-unknown-emscripten'` and default behavior should be unchanged.  When the option is set, the loader will (attempt to) use Rust's builtin wasm target and resultant boilerplate.  There are two things to note about this change:

1) Because `cargo web build` produces es6, this PR introduces a dependency on `babel-core` to transpile to es5 so webpack minification doesn't get broken.  Emscripten boilerplate is not transformed, to minimize the impact of this change.

2) The generated boilerplate JS is slightly different, and because of that, calling your generated code is as well.  Rather than `require('./lib.rs').initialize().then((app) => app.doStuff())` as with emscripten, unknown-unknown is invoked as `require('./lib.rs').then((app) => app.doStuff())` - no initialize().

I've been writing Rust with `stdweb` and canvas all weekend with this setup and it seems to be working well, but happy to look into any tweaks you'd like to see before merging.

### CODE REVIEW

**Review by ianjsikes — CHANGES_REQUESTED** [review]
Hey @germania, this is amazing, thank you. A few things:
- Let's just make `wasm32-unknown-unknown` the default. It makes things so much easier, and this way users can opt-in to the extra bulk of emscripten only if they need it.
- Can you update the README and example project to use `require(...).then`, and maybe a note in the README about the optional Emscripten target.

**Comment by germania** [comment]
Sure thing, will get to this ASAP!

**Comment by germania** [comment]
I think this ticks all of the boxes, let me know if anything else needs looking at!

**Review by ianjsikes — APPROVED** [review]
Great work!

**Pull request merged**
